-- Add most of the columns
ALTER TABLE KINGDOM_RUSH_LEVEL_STAGE ADD (
    KINGDOM_RUSH_LEVEL_STAGE_COPY_001 VARCHAR2(4000 BYTE),
    GAME_ID_COPY_001 RAW(16),
    IMAGE_COPY_001 BLOB,
    NUMBER_VALUE NUMBER,  -- New number column
    GAME_STRING VARCHAR2(4000 BYTE),  -- New game string column
    NOTE_COPY_001 VARCHAR2(4000 BYTE)
);
-- Add date columns separately
ALTER TABLE KINGDOM_RUSH_LEVEL_STAGE ADD (
    DATE_CREATED_COPY_001 TIMESTAMP(9) WITH TIME ZONE DEFAULT systimestamp(9),
    DATE_UPDATED_COPY_001 TIMESTAMP(9) WITH TIME ZONE
);
-- Finally, add the virtual column
ALTER TABLE KINGDOM_RUSH_LEVEL_STAGE ADD (
    DATE_CREATED_OR_UPDATED_COPY_001 TIMESTAMP(9) WITH TIME ZONE 
    GENERATED ALWAYS AS (COALESCE(DATE_UPDATED_COPY_001, DATE_CREATED_COPY_001)) VIRTUAL
);


CREATE OR REPLACE TRIGGER TRG_KINGDOM_RUSH_LEVEL_STAGE_UPDATE_COPY_001
BEFORE UPDATE ON KINGDOM_RUSH_LEVEL_STAGE
FOR EACH ROW
BEGIN
    :new.DATE_UPDATED_COPY_001 := systimestamp;  -- Set the update timestamp
END;
/

UPDATE KINGDOM_RUSH_LEVEL_STAGE
SET
    KINGDOM_RUSH_LEVEL_STAGE_COPY_001 = KINGDOM_RUSH_LEVEL_STAGE,
    GAME_ID_COPY_001 = GAME_ID,
    IMAGE_COPY_001 = IMAGE,
    NOTE_COPY_001 = NOTE,
    DATE_CREATED_COPY_001 = DATE_CREATED,
    DATE_UPDATED_COPY_001 = DATE_UPDATED;
